modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/Talia-12/Hexal/issues"

[[mods]]
modId = "hexal"
version = "${file.jarVersion}"
displayName = "Hexal"
displayURL = "https://github.com/Talia-12/Hexal"
logoFile = "logo.png"
credits = "petrak@ and other developers of Hex Casting for the mod that this is an addon for."
authors = "Talia"
description = ""

[[dependencies.hexal]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexal]]
modId = "paucal"
mandatory = true
versionRange = "[0.5.0,0.6.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexal]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexal]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3]"
ordering = "NONE"
side = "BOTH"
